apiVersion: apps/v1
kind: Deployment
metadata:
  name: fifth-app-v1
  labels:
    app: fifth-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fifth-app
      version: v1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fifth-app
        version: v1
    spec:
      containers:
      - name: fifth-app-v1
        image: localhost:5001/fifth-app:v1
        ports:
        - containerPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fifth-app-v2
  labels:
    app: fifth-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fifth-app
      version: v2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fifth-app
        version: v2
    spec:
      containers:
      - name: fifth-app-v2
        image: localhost:5001/fifth-app:v2
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: fifth-app
spec:
  selector:
    app: fifth-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
