apiVersion: apps/v1
kind: Deployment
metadata:
  name: fourth-app-v1
  labels:
    app: fourth-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fourth-app
      version: v1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fourth-app
        version: v1
    spec:
      containers:
      - name: fourth-app-v1
        image: localhost:5001/fourth-app:v1
        ports:
        - containerPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fourth-app-v2
  labels:
    app: fourth-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fourth-app
      version: v2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fourth-app
        version: v2
    spec:
      containers:
      - name: fourth-app-v2
        image: localhost:5001/fourth-app:v2
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: fourth-app
spec:
  selector:
    app: fourth-app
    version: v1
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: fourth-app-v2
spec:
  selector:
    app: fourth-app
    version: v2
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
