apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
    company: acme
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
      company: acme
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
        company: acme
    spec:
      containers:
      - name: app
        image: localhost:5001/app:.TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9000
      name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acme-web
spec:
  rules:
  - host: www.acme.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 9090