version: '3'

services:
  gogs:
    image: gogs/gogs
    restart: always
    volumes:
    - gogs:/data
    ports:
    - "10022:22"
    - "9001:3000"
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - "9000:8080"
    - "50000:50000"
    volumes:
    - jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: registry
    restart: always
    volumes:
    - registry:/var/lib/registry
    ports:
    - 5000:5000

volumes:
  gogs: {}
  jenkins: {}
  registry: {}
