---
- hosts: all
  vars:
    ansible_host_key_checking: false
  become: yes
  tasks:
    - { include_tasks: "tasks/configuration.yml"}
    - { include_tasks: "tasks/delete.yml"}
    - { include_tasks: "tasks/download.yml"}
  