apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app
  labels:
    app: second-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
      - name: second-app
        image: localhost:5001/second-app:v1
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: second-app
spec:
  selector:
    app: second-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
