version: '3'

services:
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
    - ./src:/app
    ports:
    - 8080:8080
    environment:
    - ENVIRONMENT=local
    - DEBUG=True
    - RELOADER=True
    - APM_NAME=bootcamp
